# Generated by Django 5.0.3 on 2024-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
